Convert readthedocs link for their .org -> .io migration for hosted projects
celery/cyanide pull request #1
Opened 2016-05-29 14:17 UTC by adamchainz

As per their email ‘Changes to project subdomains’:

> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.

Test Plan: Manually visited all the links I’ve modified.

Also the github repo link needs updating.

2018-01-27 09:34 UTC, thedrow commented
@auvipy Why did you close this issue?

2018-01-27 09:55 UTC, auvipy commented
awh my bad! I was supposed to merge it but closed subconsciously!

2018-01-27 09:56 UTC, auvipy approved these changes

2018-01-27 09:57 UTC, auvipy requested changes
need to rebase

2018-01-28 15:41 UTC, adamchainz commented
I don't have time to rebase this, please do it yourself if this project is still being maintained (no commits since 2016?)

2018-01-28 15:41 UTC, closed without merging